name: mvt-server-stack
services:
  maputnik1:
    container_name: maputnik-v170
    build:
      context: ./maputnik
      dockerfile: Dockerfile.v170
    image: lerryws/maputnik:1.7.0
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - maputnik-network
    depends_on: 
      - db
      - martin

  maputnik2:
    container_name: maputnik-latest
    build:
      context: ./maputnik
      dockerfile: Dockerfile.latest
    image: lerryws/maputnik:latest
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - maputnik-network
    depends_on: 
      - db
      - martin

  db:
    build: ./postgis
    image: lerryws/postgis:tilemill
    container_name: database
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - maputnik-network

  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin
    volumes:
      - ./configs/martin:/opt/
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - maputnik-network

  pgadmin:
    container_name: gis_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "8111:80"
    networks:
      - maputnik-network
    depends_on: 
      - db

networks:
  maputnik-network:
    driver: bridge